name: muxa_xtream
description: "Xtream API client for Dart (no UI)."
version: 0.1.0

environment:
  sdk: ^3.8.1

repository: https://github.com/felixssimoes/muxa_xtream

dependencies:
  # No Flutter dependency; pure Dart package

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
