name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Verify
        env:
          VERIFY_PUB_GET: "1"
          VERIFY_COVERAGE: "0"
        run: bash tool/verify.sh
